// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: characters.sql

package sqlcgen

import (
	"context"
)

const deleteCharacter = `-- name: DeleteCharacter :exec
DELETE FROM characters
WHERE id = ?1
`

func (q *Queries) DeleteCharacter(ctx context.Context, id string) error {
	_, err := q.db.ExecContext(ctx, deleteCharacter, id)
	return err
}

const getCharacter = `-- name: GetCharacter :one
SELECT id, name, multi_voice, voice_json, chat_json
FROM characters
WHERE id = ?1
`

func (q *Queries) GetCharacter(ctx context.Context, id string) (Character, error) {
	row := q.db.QueryRowContext(ctx, getCharacter, id)
	var i Character
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.MultiVoice,
		&i.VoiceJson,
		&i.ChatJson,
	)
	return i, err
}

const listCharacters = `-- name: ListCharacters :many
SELECT id, name, multi_voice, voice_json, chat_json
FROM characters
ORDER BY name, id
`

func (q *Queries) ListCharacters(ctx context.Context) ([]Character, error) {
	rows, err := q.db.QueryContext(ctx, listCharacters)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Character
	for rows.Next() {
		var i Character
		if err := rows.Scan(
			&i.ID,
			&i.Name,
			&i.MultiVoice,
			&i.VoiceJson,
			&i.ChatJson,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const upsertCharacter = `-- name: UpsertCharacter :exec
INSERT INTO characters (
    id,
    name,
    multi_voice,
    voice_json,
    chat_json
) VALUES (
    ?1,
    ?2,
    ?3,
    ?4,
    ?5
)
ON CONFLICT(id) DO UPDATE SET
    name = excluded.name,
    multi_voice = excluded.multi_voice,
    voice_json = excluded.voice_json,
    chat_json = excluded.chat_json
`

type UpsertCharacterParams struct {
	ID         string
	Name       string
	MultiVoice int64
	VoiceJson  string
	ChatJson   string
}

func (q *Queries) UpsertCharacter(ctx context.Context, arg UpsertCharacterParams) error {
	_, err := q.db.ExecContext(ctx, upsertCharacter,
		arg.ID,
		arg.Name,
		arg.MultiVoice,
		arg.VoiceJson,
		arg.ChatJson,
	)
	return err
}
