// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: chat_sessions.sql

package sqlcgen

import (
	"context"
)

const deleteChatSession = `-- name: DeleteChatSession :exec
DELETE FROM chat_sessions
WHERE session_id = ?1
  AND character_id = ?2
`

type DeleteChatSessionParams struct {
	SessionID   string
	CharacterID string
}

func (q *Queries) DeleteChatSession(ctx context.Context, arg DeleteChatSessionParams) error {
	_, err := q.db.ExecContext(ctx, deleteChatSession, arg.SessionID, arg.CharacterID)
	return err
}

const getChatSession = `-- name: GetChatSession :one
SELECT session_id, character_id, messages_json
FROM chat_sessions
WHERE session_id = ?1
  AND character_id = ?2
`

type GetChatSessionParams struct {
	SessionID   string
	CharacterID string
}

func (q *Queries) GetChatSession(ctx context.Context, arg GetChatSessionParams) (ChatSession, error) {
	row := q.db.QueryRowContext(ctx, getChatSession, arg.SessionID, arg.CharacterID)
	var i ChatSession
	err := row.Scan(&i.SessionID, &i.CharacterID, &i.MessagesJson)
	return i, err
}

const listChatSessions = `-- name: ListChatSessions :many
SELECT session_id, character_id, messages_json
FROM chat_sessions
ORDER BY session_id, character_id
`

func (q *Queries) ListChatSessions(ctx context.Context) ([]ChatSession, error) {
	rows, err := q.db.QueryContext(ctx, listChatSessions)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []ChatSession
	for rows.Next() {
		var i ChatSession
		if err := rows.Scan(&i.SessionID, &i.CharacterID, &i.MessagesJson); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const upsertChatSession = `-- name: UpsertChatSession :exec
INSERT INTO chat_sessions (
    session_id,
    character_id,
    messages_json
) VALUES (
    ?1,
    ?2,
    ?3
)
ON CONFLICT(session_id, character_id) DO UPDATE SET
    messages_json = excluded.messages_json
`

type UpsertChatSessionParams struct {
	SessionID    string
	CharacterID  string
	MessagesJson string
}

func (q *Queries) UpsertChatSession(ctx context.Context, arg UpsertChatSessionParams) error {
	_, err := q.db.ExecContext(ctx, upsertChatSession, arg.SessionID, arg.CharacterID, arg.MessagesJson)
	return err
}
