// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: env.sql

package sqlcgen

import (
	"context"
)

const getEnvConfig = `-- name: GetEnvConfig :one
SELECT id, openai_speech_to_text_api_key, google_speech_to_text_api_key, vosk_server_endpoint, openai_api_key, anthropic_api_key, deepseek_api_key, gemini_api_key, openai_local_api_key, openai_local_api_endpoint, voicevox_endpoint, bertvits2_endpoint, irodori_tts_endpoint, nijivoice_api_key, stylebertvit2_endpoint, google_text_to_speech_api_key, openai_speech_api_key
FROM env_config
WHERE id = 1
`

func (q *Queries) GetEnvConfig(ctx context.Context) (EnvConfig, error) {
	row := q.db.QueryRowContext(ctx, getEnvConfig)
	var i EnvConfig
	err := row.Scan(
		&i.ID,
		&i.OpenaiSpeechToTextApiKey,
		&i.GoogleSpeechToTextApiKey,
		&i.VoskServerEndpoint,
		&i.OpenaiApiKey,
		&i.AnthropicApiKey,
		&i.DeepseekApiKey,
		&i.GeminiApiKey,
		&i.OpenaiLocalApiKey,
		&i.OpenaiLocalApiEndpoint,
		&i.VoicevoxEndpoint,
		&i.Bertvits2Endpoint,
		&i.IrodoriTtsEndpoint,
		&i.NijivoiceApiKey,
		&i.Stylebertvit2Endpoint,
		&i.GoogleTextToSpeechApiKey,
		&i.OpenaiSpeechApiKey,
	)
	return i, err
}

const listEnvConfigs = `-- name: ListEnvConfigs :many
SELECT id, openai_speech_to_text_api_key, google_speech_to_text_api_key, vosk_server_endpoint, openai_api_key, anthropic_api_key, deepseek_api_key, gemini_api_key, openai_local_api_key, openai_local_api_endpoint, voicevox_endpoint, bertvits2_endpoint, irodori_tts_endpoint, nijivoice_api_key, stylebertvit2_endpoint, google_text_to_speech_api_key, openai_speech_api_key
FROM env_config
ORDER BY id
`

func (q *Queries) ListEnvConfigs(ctx context.Context) ([]EnvConfig, error) {
	rows, err := q.db.QueryContext(ctx, listEnvConfigs)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []EnvConfig
	for rows.Next() {
		var i EnvConfig
		if err := rows.Scan(
			&i.ID,
			&i.OpenaiSpeechToTextApiKey,
			&i.GoogleSpeechToTextApiKey,
			&i.VoskServerEndpoint,
			&i.OpenaiApiKey,
			&i.AnthropicApiKey,
			&i.DeepseekApiKey,
			&i.GeminiApiKey,
			&i.OpenaiLocalApiKey,
			&i.OpenaiLocalApiEndpoint,
			&i.VoicevoxEndpoint,
			&i.Bertvits2Endpoint,
			&i.IrodoriTtsEndpoint,
			&i.NijivoiceApiKey,
			&i.Stylebertvit2Endpoint,
			&i.GoogleTextToSpeechApiKey,
			&i.OpenaiSpeechApiKey,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const upsertEnvConfig = `-- name: UpsertEnvConfig :exec
INSERT INTO env_config (
    id,
    openai_speech_to_text_api_key,
    google_speech_to_text_api_key,
    vosk_server_endpoint,
    openai_api_key,
    anthropic_api_key,
    deepseek_api_key,
    gemini_api_key,
    openai_local_api_key,
    openai_local_api_endpoint,
    voicevox_endpoint,
    bertvits2_endpoint,
    irodori_tts_endpoint,
    nijivoice_api_key,
    stylebertvit2_endpoint,
    google_text_to_speech_api_key,
    openai_speech_api_key
) VALUES (
    ?1,
    ?2,
    ?3,
    ?4,
    ?5,
    ?6,
    ?7,
    ?8,
    ?9,
    ?10,
    ?11,
    ?12,
    ?13,
    ?14,
    ?15,
    ?16,
    ?17
)
ON CONFLICT(id) DO UPDATE SET
    openai_speech_to_text_api_key = excluded.openai_speech_to_text_api_key,
    google_speech_to_text_api_key = excluded.google_speech_to_text_api_key,
    vosk_server_endpoint = excluded.vosk_server_endpoint,
    openai_api_key = excluded.openai_api_key,
    anthropic_api_key = excluded.anthropic_api_key,
    deepseek_api_key = excluded.deepseek_api_key,
    gemini_api_key = excluded.gemini_api_key,
    openai_local_api_key = excluded.openai_local_api_key,
    openai_local_api_endpoint = excluded.openai_local_api_endpoint,
    voicevox_endpoint = excluded.voicevox_endpoint,
    bertvits2_endpoint = excluded.bertvits2_endpoint,
    irodori_tts_endpoint = excluded.irodori_tts_endpoint,
    nijivoice_api_key = excluded.nijivoice_api_key,
    stylebertvit2_endpoint = excluded.stylebertvit2_endpoint,
    google_text_to_speech_api_key = excluded.google_text_to_speech_api_key,
    openai_speech_api_key = excluded.openai_speech_api_key
`

type UpsertEnvConfigParams struct {
	ID                       int64
	OpenaiSpeechToTextApiKey string
	GoogleSpeechToTextApiKey string
	VoskServerEndpoint       string
	OpenaiApiKey             string
	AnthropicApiKey          string
	DeepseekApiKey           string
	GeminiApiKey             string
	OpenaiLocalApiKey        string
	OpenaiLocalApiEndpoint   string
	VoicevoxEndpoint         string
	Bertvits2Endpoint        string
	IrodoriTtsEndpoint       string
	NijivoiceApiKey          string
	Stylebertvit2Endpoint    string
	GoogleTextToSpeechApiKey string
	OpenaiSpeechApiKey       string
}

func (q *Queries) UpsertEnvConfig(ctx context.Context, arg UpsertEnvConfigParams) error {
	_, err := q.db.ExecContext(ctx, upsertEnvConfig,
		arg.ID,
		arg.OpenaiSpeechToTextApiKey,
		arg.GoogleSpeechToTextApiKey,
		arg.VoskServerEndpoint,
		arg.OpenaiApiKey,
		arg.AnthropicApiKey,
		arg.DeepseekApiKey,
		arg.GeminiApiKey,
		arg.OpenaiLocalApiKey,
		arg.OpenaiLocalApiEndpoint,
		arg.VoicevoxEndpoint,
		arg.Bertvits2Endpoint,
		arg.IrodoriTtsEndpoint,
		arg.NijivoiceApiKey,
		arg.Stylebertvit2Endpoint,
		arg.GoogleTextToSpeechApiKey,
		arg.OpenaiSpeechApiKey,
	)
	return err
}
