// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: general.sql

package sqlcgen

import (
	"context"
)

const getGeneralConfig = `-- name: GetGeneralConfig :one
SELECT id, background, language, sound_effect, character_output_change, enable_tts_optimization, transcription_type, transcription_method, transcription_auto_threshold, transcription_auto_silent_threshold, transcription_auto_audio_min_length
FROM general_config
WHERE id = 1
`

func (q *Queries) GetGeneralConfig(ctx context.Context) (GeneralConfig, error) {
	row := q.db.QueryRowContext(ctx, getGeneralConfig)
	var i GeneralConfig
	err := row.Scan(
		&i.ID,
		&i.Background,
		&i.Language,
		&i.SoundEffect,
		&i.CharacterOutputChange,
		&i.EnableTtsOptimization,
		&i.TranscriptionType,
		&i.TranscriptionMethod,
		&i.TranscriptionAutoThreshold,
		&i.TranscriptionAutoSilentThreshold,
		&i.TranscriptionAutoAudioMinLength,
	)
	return i, err
}

const listGeneralConfigs = `-- name: ListGeneralConfigs :many
SELECT id, background, language, sound_effect, character_output_change, enable_tts_optimization, transcription_type, transcription_method, transcription_auto_threshold, transcription_auto_silent_threshold, transcription_auto_audio_min_length
FROM general_config
ORDER BY id
`

func (q *Queries) ListGeneralConfigs(ctx context.Context) ([]GeneralConfig, error) {
	rows, err := q.db.QueryContext(ctx, listGeneralConfigs)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []GeneralConfig
	for rows.Next() {
		var i GeneralConfig
		if err := rows.Scan(
			&i.ID,
			&i.Background,
			&i.Language,
			&i.SoundEffect,
			&i.CharacterOutputChange,
			&i.EnableTtsOptimization,
			&i.TranscriptionType,
			&i.TranscriptionMethod,
			&i.TranscriptionAutoThreshold,
			&i.TranscriptionAutoSilentThreshold,
			&i.TranscriptionAutoAudioMinLength,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const upsertGeneralConfig = `-- name: UpsertGeneralConfig :exec
INSERT INTO general_config (
    id,
    background,
    language,
    sound_effect,
    character_output_change,
    enable_tts_optimization,
    transcription_type,
    transcription_method,
    transcription_auto_threshold,
    transcription_auto_silent_threshold,
    transcription_auto_audio_min_length
) VALUES (
    ?1,
    ?2,
    ?3,
    ?4,
    ?5,
    ?6,
    ?7,
    ?8,
    ?9,
    ?10,
    ?11
)
ON CONFLICT(id) DO UPDATE SET
    background = excluded.background,
    language = excluded.language,
    sound_effect = excluded.sound_effect,
    character_output_change = excluded.character_output_change,
    enable_tts_optimization = excluded.enable_tts_optimization,
    transcription_type = excluded.transcription_type,
    transcription_method = excluded.transcription_method,
    transcription_auto_threshold = excluded.transcription_auto_threshold,
    transcription_auto_silent_threshold = excluded.transcription_auto_silent_threshold,
    transcription_auto_audio_min_length = excluded.transcription_auto_audio_min_length
`

type UpsertGeneralConfigParams struct {
	ID                               int64
	Background                       string
	Language                         string
	SoundEffect                      int64
	CharacterOutputChange            int64
	EnableTtsOptimization            int64
	TranscriptionType                string
	TranscriptionMethod              string
	TranscriptionAutoThreshold       float64
	TranscriptionAutoSilentThreshold float64
	TranscriptionAutoAudioMinLength  float64
}

func (q *Queries) UpsertGeneralConfig(ctx context.Context, arg UpsertGeneralConfigParams) error {
	_, err := q.db.ExecContext(ctx, upsertGeneralConfig,
		arg.ID,
		arg.Background,
		arg.Language,
		arg.SoundEffect,
		arg.CharacterOutputChange,
		arg.EnableTtsOptimization,
		arg.TranscriptionType,
		arg.TranscriptionMethod,
		arg.TranscriptionAutoThreshold,
		arg.TranscriptionAutoSilentThreshold,
		arg.TranscriptionAutoAudioMinLength,
	)
	return err
}
