// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: memory.sql

package sqlcgen

import (
	"context"
	"database/sql"
)

const countMemoryJobs = `-- name: CountMemoryJobs :one
SELECT COUNT(*)
FROM memory_jobs
`

func (q *Queries) CountMemoryJobs(ctx context.Context) (int64, error) {
	row := q.db.QueryRowContext(ctx, countMemoryJobs)
	var count int64
	err := row.Scan(&count)
	return count, err
}

const deleteMemoryItemByPublicID = `-- name: DeleteMemoryItemByPublicID :exec
DELETE FROM memory_items
WHERE public_id = ?1
`

func (q *Queries) DeleteMemoryItemByPublicID(ctx context.Context, publicID string) error {
	_, err := q.db.ExecContext(ctx, deleteMemoryItemByPublicID, publicID)
	return err
}

const deleteMemoryJob = `-- name: DeleteMemoryJob :exec
DELETE FROM memory_jobs
WHERE id = ?1
`

func (q *Queries) DeleteMemoryJob(ctx context.Context, id int64) error {
	_, err := q.db.ExecContext(ctx, deleteMemoryJob, id)
	return err
}

const getCharacterMemorySetting = `-- name: GetCharacterMemorySetting :one
SELECT
    character_id,
    enabled,
    max_items_in_prompt,
    enable_relationship_memory,
    enable_session_summary,
    enable_semantic_search,
    embedding_model,
    allow_sensitive_memory
FROM character_memory_settings
WHERE character_id = ?1
`

func (q *Queries) GetCharacterMemorySetting(ctx context.Context, characterID string) (CharacterMemorySetting, error) {
	row := q.db.QueryRowContext(ctx, getCharacterMemorySetting, characterID)
	var i CharacterMemorySetting
	err := row.Scan(
		&i.CharacterID,
		&i.Enabled,
		&i.MaxItemsInPrompt,
		&i.EnableRelationshipMemory,
		&i.EnableSessionSummary,
		&i.EnableSemanticSearch,
		&i.EmbeddingModel,
		&i.AllowSensitiveMemory,
	)
	return i, err
}

const getMemoryItemByPublicID = `-- name: GetMemoryItemByPublicID :one
SELECT
    id,
    public_id,
    character_id,
    owner_id,
    scope,
    kind,
    content,
    normalized_content,
    keywords_text,
    pinned,
    confidence,
    salience,
    source,
    superseded_by,
    embedding_json,
    created_at,
    updated_at,
    last_accessed_at
FROM memory_items
WHERE public_id = ?1
`

func (q *Queries) GetMemoryItemByPublicID(ctx context.Context, publicID string) (MemoryItem, error) {
	row := q.db.QueryRowContext(ctx, getMemoryItemByPublicID, publicID)
	var i MemoryItem
	err := row.Scan(
		&i.ID,
		&i.PublicID,
		&i.CharacterID,
		&i.OwnerID,
		&i.Scope,
		&i.Kind,
		&i.Content,
		&i.NormalizedContent,
		&i.KeywordsText,
		&i.Pinned,
		&i.Confidence,
		&i.Salience,
		&i.Source,
		&i.SupersededBy,
		&i.EmbeddingJson,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.LastAccessedAt,
	)
	return i, err
}

const getNextQueuedMemoryJob = `-- name: GetNextQueuedMemoryJob :one
SELECT
    id,
    type,
    status,
    unique_key,
    payload_json,
    attempts,
    available_at,
    created_at,
    updated_at,
    last_error
FROM memory_jobs
WHERE status = ?1
  AND available_at <= ?2
ORDER BY available_at ASC, id ASC
LIMIT 1
`

type GetNextQueuedMemoryJobParams struct {
	Status      string
	AvailableAt string
}

func (q *Queries) GetNextQueuedMemoryJob(ctx context.Context, arg GetNextQueuedMemoryJobParams) (MemoryJob, error) {
	row := q.db.QueryRowContext(ctx, getNextQueuedMemoryJob, arg.Status, arg.AvailableAt)
	var i MemoryJob
	err := row.Scan(
		&i.ID,
		&i.Type,
		&i.Status,
		&i.UniqueKey,
		&i.PayloadJson,
		&i.Attempts,
		&i.AvailableAt,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.LastError,
	)
	return i, err
}

const getSessionSummary = `-- name: GetSessionSummary :one
SELECT
    owner_id,
    character_id,
    session_id,
    summary,
    updated_at
FROM session_summaries
WHERE owner_id = ?1
  AND character_id = ?2
  AND session_id = ?3
`

type GetSessionSummaryParams struct {
	OwnerID     string
	CharacterID string
	SessionID   string
}

func (q *Queries) GetSessionSummary(ctx context.Context, arg GetSessionSummaryParams) (SessionSummary, error) {
	row := q.db.QueryRowContext(ctx, getSessionSummary, arg.OwnerID, arg.CharacterID, arg.SessionID)
	var i SessionSummary
	err := row.Scan(
		&i.OwnerID,
		&i.CharacterID,
		&i.SessionID,
		&i.Summary,
		&i.UpdatedAt,
	)
	return i, err
}

const insertMemoryItem = `-- name: InsertMemoryItem :execresult
INSERT INTO memory_items (
    public_id,
    character_id,
    owner_id,
    scope,
    kind,
    content,
    normalized_content,
    keywords_text,
    pinned,
    confidence,
    salience,
    source,
    superseded_by,
    embedding_json,
    created_at,
    updated_at,
    last_accessed_at
) VALUES (
    ?1,
    ?2,
    ?3,
    ?4,
    ?5,
    ?6,
    ?7,
    ?8,
    ?9,
    ?10,
    ?11,
    ?12,
    ?13,
    ?14,
    ?15,
    ?16,
    ?17
)
`

type InsertMemoryItemParams struct {
	PublicID          string
	CharacterID       string
	OwnerID           string
	Scope             string
	Kind              string
	Content           string
	NormalizedContent string
	KeywordsText      string
	Pinned            int64
	Confidence        float64
	Salience          float64
	Source            string
	SupersededBy      sql.NullInt64
	EmbeddingJson     string
	CreatedAt         string
	UpdatedAt         string
	LastAccessedAt    string
}

func (q *Queries) InsertMemoryItem(ctx context.Context, arg InsertMemoryItemParams) (sql.Result, error) {
	return q.db.ExecContext(ctx, insertMemoryItem,
		arg.PublicID,
		arg.CharacterID,
		arg.OwnerID,
		arg.Scope,
		arg.Kind,
		arg.Content,
		arg.NormalizedContent,
		arg.KeywordsText,
		arg.Pinned,
		arg.Confidence,
		arg.Salience,
		arg.Source,
		arg.SupersededBy,
		arg.EmbeddingJson,
		arg.CreatedAt,
		arg.UpdatedAt,
		arg.LastAccessedAt,
	)
}

const insertMemoryItemEvidence = `-- name: InsertMemoryItemEvidence :exec
INSERT INTO memory_item_evidence (
    memory_item_id,
    session_id,
    message_index_start,
    message_index_end,
    excerpt,
    created_at
) VALUES (
    ?1,
    ?2,
    ?3,
    ?4,
    ?5,
    ?6
)
`

type InsertMemoryItemEvidenceParams struct {
	MemoryItemID      int64
	SessionID         string
	MessageIndexStart int64
	MessageIndexEnd   int64
	Excerpt           string
	CreatedAt         string
}

func (q *Queries) InsertMemoryItemEvidence(ctx context.Context, arg InsertMemoryItemEvidenceParams) error {
	_, err := q.db.ExecContext(ctx, insertMemoryItemEvidence,
		arg.MemoryItemID,
		arg.SessionID,
		arg.MessageIndexStart,
		arg.MessageIndexEnd,
		arg.Excerpt,
		arg.CreatedAt,
	)
	return err
}

const insertMemoryJobIgnoreConflict = `-- name: InsertMemoryJobIgnoreConflict :exec
INSERT INTO memory_jobs (
    type,
    status,
    unique_key,
    payload_json,
    attempts,
    available_at,
    created_at,
    updated_at,
    last_error
) VALUES (
    ?1,
    ?2,
    ?3,
    ?4,
    ?5,
    ?6,
    ?7,
    ?8,
    ?9
)
ON CONFLICT(unique_key) DO NOTHING
`

type InsertMemoryJobIgnoreConflictParams struct {
	Type        string
	Status      string
	UniqueKey   string
	PayloadJson string
	Attempts    int64
	AvailableAt string
	CreatedAt   string
	UpdatedAt   string
	LastError   string
}

func (q *Queries) InsertMemoryJobIgnoreConflict(ctx context.Context, arg InsertMemoryJobIgnoreConflictParams) error {
	_, err := q.db.ExecContext(ctx, insertMemoryJobIgnoreConflict,
		arg.Type,
		arg.Status,
		arg.UniqueKey,
		arg.PayloadJson,
		arg.Attempts,
		arg.AvailableAt,
		arg.CreatedAt,
		arg.UpdatedAt,
		arg.LastError,
	)
	return err
}

const listActiveRelationshipMemory = `-- name: ListActiveRelationshipMemory :many
SELECT
    id,
    public_id,
    character_id,
    owner_id,
    scope,
    kind,
    content,
    normalized_content,
    keywords_text,
    pinned,
    confidence,
    salience,
    source,
    superseded_by,
    embedding_json,
    created_at,
    updated_at,
    last_accessed_at
FROM memory_items
WHERE character_id = ?1
  AND owner_id = ?2
  AND scope = 'relationship'
  AND superseded_by IS NULL
`

type ListActiveRelationshipMemoryParams struct {
	CharacterID string
	OwnerID     string
}

func (q *Queries) ListActiveRelationshipMemory(ctx context.Context, arg ListActiveRelationshipMemoryParams) ([]MemoryItem, error) {
	rows, err := q.db.QueryContext(ctx, listActiveRelationshipMemory, arg.CharacterID, arg.OwnerID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []MemoryItem
	for rows.Next() {
		var i MemoryItem
		if err := rows.Scan(
			&i.ID,
			&i.PublicID,
			&i.CharacterID,
			&i.OwnerID,
			&i.Scope,
			&i.Kind,
			&i.Content,
			&i.NormalizedContent,
			&i.KeywordsText,
			&i.Pinned,
			&i.Confidence,
			&i.Salience,
			&i.Source,
			&i.SupersededBy,
			&i.EmbeddingJson,
			&i.CreatedAt,
			&i.UpdatedAt,
			&i.LastAccessedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listMemoryItemsForOwnerAndCharacter = `-- name: ListMemoryItemsForOwnerAndCharacter :many
SELECT
    id,
    public_id,
    character_id,
    owner_id,
    scope,
    kind,
    content,
    normalized_content,
    keywords_text,
    pinned,
    confidence,
    salience,
    source,
    superseded_by,
    embedding_json,
    created_at,
    updated_at,
    last_accessed_at
FROM memory_items
WHERE character_id = ?1
  AND superseded_by IS NULL
  AND (
    (scope = 'character' AND owner_id = '')
    OR (scope = 'relationship' AND owner_id = ?2)
  )
ORDER BY pinned DESC, updated_at DESC, id DESC
`

type ListMemoryItemsForOwnerAndCharacterParams struct {
	CharacterID string
	OwnerID     string
}

func (q *Queries) ListMemoryItemsForOwnerAndCharacter(ctx context.Context, arg ListMemoryItemsForOwnerAndCharacterParams) ([]MemoryItem, error) {
	rows, err := q.db.QueryContext(ctx, listMemoryItemsForOwnerAndCharacter, arg.CharacterID, arg.OwnerID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []MemoryItem
	for rows.Next() {
		var i MemoryItem
		if err := rows.Scan(
			&i.ID,
			&i.PublicID,
			&i.CharacterID,
			&i.OwnerID,
			&i.Scope,
			&i.Kind,
			&i.Content,
			&i.NormalizedContent,
			&i.KeywordsText,
			&i.Pinned,
			&i.Confidence,
			&i.Salience,
			&i.Source,
			&i.SupersededBy,
			&i.EmbeddingJson,
			&i.CreatedAt,
			&i.UpdatedAt,
			&i.LastAccessedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listMemoryRecordsForCharacter = `-- name: ListMemoryRecordsForCharacter :many
SELECT
    id,
    public_id,
    character_id,
    owner_id,
    scope,
    kind,
    content,
    normalized_content,
    keywords_text,
    pinned,
    confidence,
    salience,
    source,
    superseded_by,
    embedding_json,
    created_at,
    updated_at,
    last_accessed_at
FROM memory_items
WHERE character_id = ?1
  AND superseded_by IS NULL
  AND (
    owner_id = ''
    OR owner_id = ?2
  )
ORDER BY id
`

type ListMemoryRecordsForCharacterParams struct {
	CharacterID string
	OwnerID     string
}

func (q *Queries) ListMemoryRecordsForCharacter(ctx context.Context, arg ListMemoryRecordsForCharacterParams) ([]MemoryItem, error) {
	rows, err := q.db.QueryContext(ctx, listMemoryRecordsForCharacter, arg.CharacterID, arg.OwnerID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []MemoryItem
	for rows.Next() {
		var i MemoryItem
		if err := rows.Scan(
			&i.ID,
			&i.PublicID,
			&i.CharacterID,
			&i.OwnerID,
			&i.Scope,
			&i.Kind,
			&i.Content,
			&i.NormalizedContent,
			&i.KeywordsText,
			&i.Pinned,
			&i.Confidence,
			&i.Salience,
			&i.Source,
			&i.SupersededBy,
			&i.EmbeddingJson,
			&i.CreatedAt,
			&i.UpdatedAt,
			&i.LastAccessedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listPinnedMemoryCandidatesCharacterOnly = `-- name: ListPinnedMemoryCandidatesCharacterOnly :many
SELECT
    id,
    public_id,
    character_id,
    owner_id,
    scope,
    kind,
    content,
    normalized_content,
    keywords_text,
    pinned,
    confidence,
    salience,
    source,
    superseded_by,
    embedding_json,
    created_at,
    updated_at,
    last_accessed_at
FROM memory_items
WHERE character_id = ?1
  AND superseded_by IS NULL
  AND pinned = 1
  AND scope = 'character'
  AND owner_id = ''
ORDER BY updated_at DESC
LIMIT ?2
`

type ListPinnedMemoryCandidatesCharacterOnlyParams struct {
	CharacterID string
	LimitRows   int64
}

func (q *Queries) ListPinnedMemoryCandidatesCharacterOnly(ctx context.Context, arg ListPinnedMemoryCandidatesCharacterOnlyParams) ([]MemoryItem, error) {
	rows, err := q.db.QueryContext(ctx, listPinnedMemoryCandidatesCharacterOnly, arg.CharacterID, arg.LimitRows)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []MemoryItem
	for rows.Next() {
		var i MemoryItem
		if err := rows.Scan(
			&i.ID,
			&i.PublicID,
			&i.CharacterID,
			&i.OwnerID,
			&i.Scope,
			&i.Kind,
			&i.Content,
			&i.NormalizedContent,
			&i.KeywordsText,
			&i.Pinned,
			&i.Confidence,
			&i.Salience,
			&i.Source,
			&i.SupersededBy,
			&i.EmbeddingJson,
			&i.CreatedAt,
			&i.UpdatedAt,
			&i.LastAccessedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listPinnedMemoryCandidatesWithRelationship = `-- name: ListPinnedMemoryCandidatesWithRelationship :many
SELECT
    id,
    public_id,
    character_id,
    owner_id,
    scope,
    kind,
    content,
    normalized_content,
    keywords_text,
    pinned,
    confidence,
    salience,
    source,
    superseded_by,
    embedding_json,
    created_at,
    updated_at,
    last_accessed_at
FROM memory_items
WHERE character_id = ?1
  AND superseded_by IS NULL
  AND pinned = 1
  AND (
    (scope = 'character' AND owner_id = '')
    OR (scope = 'relationship' AND owner_id = ?2)
  )
ORDER BY updated_at DESC
LIMIT ?3
`

type ListPinnedMemoryCandidatesWithRelationshipParams struct {
	CharacterID string
	OwnerID     string
	LimitRows   int64
}

func (q *Queries) ListPinnedMemoryCandidatesWithRelationship(ctx context.Context, arg ListPinnedMemoryCandidatesWithRelationshipParams) ([]MemoryItem, error) {
	rows, err := q.db.QueryContext(ctx, listPinnedMemoryCandidatesWithRelationship, arg.CharacterID, arg.OwnerID, arg.LimitRows)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []MemoryItem
	for rows.Next() {
		var i MemoryItem
		if err := rows.Scan(
			&i.ID,
			&i.PublicID,
			&i.CharacterID,
			&i.OwnerID,
			&i.Scope,
			&i.Kind,
			&i.Content,
			&i.NormalizedContent,
			&i.KeywordsText,
			&i.Pinned,
			&i.Confidence,
			&i.Salience,
			&i.Source,
			&i.SupersededBy,
			&i.EmbeddingJson,
			&i.CreatedAt,
			&i.UpdatedAt,
			&i.LastAccessedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const markMemoryJobRunning = `-- name: MarkMemoryJobRunning :exec
UPDATE memory_jobs
SET status = ?1,
    attempts = attempts + 1,
    updated_at = ?2
WHERE id = ?3
`

type MarkMemoryJobRunningParams struct {
	Status    string
	UpdatedAt string
	ID        int64
}

func (q *Queries) MarkMemoryJobRunning(ctx context.Context, arg MarkMemoryJobRunningParams) error {
	_, err := q.db.ExecContext(ctx, markMemoryJobRunning, arg.Status, arg.UpdatedAt, arg.ID)
	return err
}

const recoverRunningMemoryJobs = `-- name: RecoverRunningMemoryJobs :exec
UPDATE memory_jobs
SET status = ?1,
    updated_at = ?2
WHERE status = ?3
`

type RecoverRunningMemoryJobsParams struct {
	Status         string
	UpdatedAt      string
	PreviousStatus string
}

func (q *Queries) RecoverRunningMemoryJobs(ctx context.Context, arg RecoverRunningMemoryJobsParams) error {
	_, err := q.db.ExecContext(ctx, recoverRunningMemoryJobs, arg.Status, arg.UpdatedAt, arg.PreviousStatus)
	return err
}

const searchMemoryFallbackCharacterOnly = `-- name: SearchMemoryFallbackCharacterOnly :many
SELECT
    id,
    public_id,
    character_id,
    owner_id,
    scope,
    kind,
    content,
    normalized_content,
    keywords_text,
    pinned,
    confidence,
    salience,
    source,
    superseded_by,
    embedding_json,
    created_at,
    updated_at,
    last_accessed_at,
    0.0 AS lexical_raw
FROM memory_items
WHERE character_id = ?1
  AND superseded_by IS NULL
  AND scope = 'character'
  AND owner_id = ''
  AND (
    normalized_content LIKE '%' || ?2 || '%'
    OR keywords_text LIKE '%' || ?2 || '%'
  )
ORDER BY pinned DESC, updated_at DESC
LIMIT ?3
`

type SearchMemoryFallbackCharacterOnlyParams struct {
	CharacterID string
	Query       sql.NullString
	LimitRows   int64
}

type SearchMemoryFallbackCharacterOnlyRow struct {
	ID                int64
	PublicID          string
	CharacterID       string
	OwnerID           string
	Scope             string
	Kind              string
	Content           string
	NormalizedContent string
	KeywordsText      string
	Pinned            int64
	Confidence        float64
	Salience          float64
	Source            string
	SupersededBy      sql.NullInt64
	EmbeddingJson     string
	CreatedAt         string
	UpdatedAt         string
	LastAccessedAt    string
	LexicalRaw        int64
}

func (q *Queries) SearchMemoryFallbackCharacterOnly(ctx context.Context, arg SearchMemoryFallbackCharacterOnlyParams) ([]SearchMemoryFallbackCharacterOnlyRow, error) {
	rows, err := q.db.QueryContext(ctx, searchMemoryFallbackCharacterOnly, arg.CharacterID, arg.Query, arg.LimitRows)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []SearchMemoryFallbackCharacterOnlyRow
	for rows.Next() {
		var i SearchMemoryFallbackCharacterOnlyRow
		if err := rows.Scan(
			&i.ID,
			&i.PublicID,
			&i.CharacterID,
			&i.OwnerID,
			&i.Scope,
			&i.Kind,
			&i.Content,
			&i.NormalizedContent,
			&i.KeywordsText,
			&i.Pinned,
			&i.Confidence,
			&i.Salience,
			&i.Source,
			&i.SupersededBy,
			&i.EmbeddingJson,
			&i.CreatedAt,
			&i.UpdatedAt,
			&i.LastAccessedAt,
			&i.LexicalRaw,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const searchMemoryFallbackWithRelationship = `-- name: SearchMemoryFallbackWithRelationship :many
SELECT
    id,
    public_id,
    character_id,
    owner_id,
    scope,
    kind,
    content,
    normalized_content,
    keywords_text,
    pinned,
    confidence,
    salience,
    source,
    superseded_by,
    embedding_json,
    created_at,
    updated_at,
    last_accessed_at,
    0.0 AS lexical_raw
FROM memory_items
WHERE character_id = ?1
  AND superseded_by IS NULL
  AND (
    (scope = 'character' AND owner_id = '')
    OR (scope = 'relationship' AND owner_id = ?2)
  )
  AND (
    normalized_content LIKE '%' || ?3 || '%'
    OR keywords_text LIKE '%' || ?3 || '%'
  )
ORDER BY pinned DESC, updated_at DESC
LIMIT ?4
`

type SearchMemoryFallbackWithRelationshipParams struct {
	CharacterID string
	OwnerID     string
	Query       sql.NullString
	LimitRows   int64
}

type SearchMemoryFallbackWithRelationshipRow struct {
	ID                int64
	PublicID          string
	CharacterID       string
	OwnerID           string
	Scope             string
	Kind              string
	Content           string
	NormalizedContent string
	KeywordsText      string
	Pinned            int64
	Confidence        float64
	Salience          float64
	Source            string
	SupersededBy      sql.NullInt64
	EmbeddingJson     string
	CreatedAt         string
	UpdatedAt         string
	LastAccessedAt    string
	LexicalRaw        int64
}

func (q *Queries) SearchMemoryFallbackWithRelationship(ctx context.Context, arg SearchMemoryFallbackWithRelationshipParams) ([]SearchMemoryFallbackWithRelationshipRow, error) {
	rows, err := q.db.QueryContext(ctx, searchMemoryFallbackWithRelationship,
		arg.CharacterID,
		arg.OwnerID,
		arg.Query,
		arg.LimitRows,
	)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []SearchMemoryFallbackWithRelationshipRow
	for rows.Next() {
		var i SearchMemoryFallbackWithRelationshipRow
		if err := rows.Scan(
			&i.ID,
			&i.PublicID,
			&i.CharacterID,
			&i.OwnerID,
			&i.Scope,
			&i.Kind,
			&i.Content,
			&i.NormalizedContent,
			&i.KeywordsText,
			&i.Pinned,
			&i.Confidence,
			&i.Salience,
			&i.Source,
			&i.SupersededBy,
			&i.EmbeddingJson,
			&i.CreatedAt,
			&i.UpdatedAt,
			&i.LastAccessedAt,
			&i.LexicalRaw,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const supersedeMemoryItem = `-- name: SupersedeMemoryItem :exec
UPDATE memory_items
SET superseded_by = ?1
WHERE id = ?2
`

type SupersedeMemoryItemParams struct {
	SupersededBy sql.NullInt64
	ID           int64
}

func (q *Queries) SupersedeMemoryItem(ctx context.Context, arg SupersedeMemoryItemParams) error {
	_, err := q.db.ExecContext(ctx, supersedeMemoryItem, arg.SupersededBy, arg.ID)
	return err
}

const updateMemoryItemEditable = `-- name: UpdateMemoryItemEditable :exec
UPDATE memory_items
SET kind = ?1,
    content = ?2,
    normalized_content = ?3,
    keywords_text = ?4,
    pinned = ?5,
    confidence = ?6,
    salience = ?7,
    updated_at = ?8,
    last_accessed_at = ?9
WHERE id = ?10
`

type UpdateMemoryItemEditableParams struct {
	Kind              string
	Content           string
	NormalizedContent string
	KeywordsText      string
	Pinned            int64
	Confidence        float64
	Salience          float64
	UpdatedAt         string
	LastAccessedAt    string
	ID                int64
}

func (q *Queries) UpdateMemoryItemEditable(ctx context.Context, arg UpdateMemoryItemEditableParams) error {
	_, err := q.db.ExecContext(ctx, updateMemoryItemEditable,
		arg.Kind,
		arg.Content,
		arg.NormalizedContent,
		arg.KeywordsText,
		arg.Pinned,
		arg.Confidence,
		arg.Salience,
		arg.UpdatedAt,
		arg.LastAccessedAt,
		arg.ID,
	)
	return err
}

const updateMemoryItemIndex = `-- name: UpdateMemoryItemIndex :exec
UPDATE memory_items
SET normalized_content = ?1,
    keywords_text = ?2,
    embedding_json = ?3,
    updated_at = ?4
WHERE id = ?5
`

type UpdateMemoryItemIndexParams struct {
	NormalizedContent string
	KeywordsText      string
	EmbeddingJson     string
	UpdatedAt         string
	ID                int64
}

func (q *Queries) UpdateMemoryItemIndex(ctx context.Context, arg UpdateMemoryItemIndexParams) error {
	_, err := q.db.ExecContext(ctx, updateMemoryItemIndex,
		arg.NormalizedContent,
		arg.KeywordsText,
		arg.EmbeddingJson,
		arg.UpdatedAt,
		arg.ID,
	)
	return err
}

const updateMemoryJobFailure = `-- name: UpdateMemoryJobFailure :exec
UPDATE memory_jobs
SET status = ?1,
    available_at = ?2,
    updated_at = ?3,
    last_error = ?4
WHERE id = ?5
`

type UpdateMemoryJobFailureParams struct {
	Status      string
	AvailableAt string
	UpdatedAt   string
	LastError   string
	ID          int64
}

func (q *Queries) UpdateMemoryJobFailure(ctx context.Context, arg UpdateMemoryJobFailureParams) error {
	_, err := q.db.ExecContext(ctx, updateMemoryJobFailure,
		arg.Status,
		arg.AvailableAt,
		arg.UpdatedAt,
		arg.LastError,
		arg.ID,
	)
	return err
}

const upsertCharacterMemorySetting = `-- name: UpsertCharacterMemorySetting :exec
INSERT INTO character_memory_settings (
    character_id,
    enabled,
    max_items_in_prompt,
    enable_relationship_memory,
    enable_session_summary,
    enable_semantic_search,
    embedding_model,
    allow_sensitive_memory
) VALUES (
    ?1,
    ?2,
    ?3,
    ?4,
    ?5,
    ?6,
    ?7,
    ?8
)
ON CONFLICT(character_id) DO UPDATE SET
    enabled = excluded.enabled,
    max_items_in_prompt = excluded.max_items_in_prompt,
    enable_relationship_memory = excluded.enable_relationship_memory,
    enable_session_summary = excluded.enable_session_summary,
    enable_semantic_search = excluded.enable_semantic_search,
    embedding_model = excluded.embedding_model,
    allow_sensitive_memory = excluded.allow_sensitive_memory
`

type UpsertCharacterMemorySettingParams struct {
	CharacterID              string
	Enabled                  int64
	MaxItemsInPrompt         int64
	EnableRelationshipMemory int64
	EnableSessionSummary     int64
	EnableSemanticSearch     int64
	EmbeddingModel           string
	AllowSensitiveMemory     int64
}

func (q *Queries) UpsertCharacterMemorySetting(ctx context.Context, arg UpsertCharacterMemorySettingParams) error {
	_, err := q.db.ExecContext(ctx, upsertCharacterMemorySetting,
		arg.CharacterID,
		arg.Enabled,
		arg.MaxItemsInPrompt,
		arg.EnableRelationshipMemory,
		arg.EnableSessionSummary,
		arg.EnableSemanticSearch,
		arg.EmbeddingModel,
		arg.AllowSensitiveMemory,
	)
	return err
}

const upsertSessionSummary = `-- name: UpsertSessionSummary :exec
INSERT INTO session_summaries (
    owner_id,
    character_id,
    session_id,
    summary,
    updated_at
) VALUES (
    ?1,
    ?2,
    ?3,
    ?4,
    ?5
)
ON CONFLICT(owner_id, character_id, session_id) DO UPDATE SET
    summary = excluded.summary,
    updated_at = excluded.updated_at
`

type UpsertSessionSummaryParams struct {
	OwnerID     string
	CharacterID string
	SessionID   string
	Summary     string
	UpdatedAt   string
}

func (q *Queries) UpsertSessionSummary(ctx context.Context, arg UpsertSessionSummaryParams) error {
	_, err := q.db.ExecContext(ctx, upsertSessionSummary,
		arg.OwnerID,
		arg.CharacterID,
		arg.SessionID,
		arg.Summary,
		arg.UpdatedAt,
	)
	return err
}
