// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0

package sqlcgen

type Character struct {
	ID         string
	Name       string
	MultiVoice int64
	VoiceJson  string
	ChatJson   string
}

type ChatSession struct {
	SessionID    string
	CharacterID  string
	MessagesJson string
}

type EnvConfig struct {
	ID                       int64
	OpenaiSpeechToTextApiKey string
	GoogleSpeechToTextApiKey string
	VoskServerEndpoint       string
	OpenaiApiKey             string
	AnthropicApiKey          string
	DeepseekApiKey           string
	GeminiApiKey             string
	OpenaiLocalApiKey        string
	OpenaiLocalApiEndpoint   string
	VoicevoxEndpoint         string
	Bertvits2Endpoint        string
	IrodoriTtsEndpoint       string
	NijivoiceApiKey          string
	Stylebertvit2Endpoint    string
	GoogleTextToSpeechApiKey string
	OpenaiSpeechApiKey       string
}

type GeneralConfig struct {
	ID                               int64
	Background                       string
	Language                         string
	SoundEffect                      int64
	CharacterOutputChange            int64
	EnableTtsOptimization            int64
	TranscriptionType                string
	TranscriptionMethod              string
	TranscriptionAutoThreshold       float64
	TranscriptionAutoSilentThreshold float64
	TranscriptionAutoAudioMinLength  float64
}

type RateLimit struct {
	ID               string
	DayLastUpdate    string
	DayRequest       int64
	DayToken         int64
	HourLastUpdate   string
	HourRequest      int64
	HourToken        int64
	MinuteLastUpdate string
	MinuteRequest    int64
	MinuteToken      int64
}
