// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0

package sqlcgen

import (
	"database/sql"
)

type Character struct {
	ID         string
	Name       string
	MultiVoice int64
}

type CharacterChatLimit struct {
	CharacterID  string
	Window       string
	RequestLimit int64
	TokenLimit   int64
}

type CharacterChatSetting struct {
	CharacterID       string
	Type              string
	Model             string
	SystemPrompt      string
	TemperatureEnable int64
	TemperatureValue  float64
	MaxHistory        int64
}

type CharacterMemorySetting struct {
	CharacterID              string
	Enabled                  int64
	MaxItemsInPrompt         int64
	EnableRelationshipMemory int64
	EnableSessionSummary     int64
	EnableSemanticSearch     int64
	EmbeddingModel           string
	AllowSensitiveMemory     int64
}

type CharacterVoice struct {
	CharacterID         string
	VoiceIndex          int64
	Name                string
	Type                string
	Identification      string
	ModelID             string
	ModelFile           string
	SpeakerID           string
	ReferenceAudioPath  string
	Image               string
	BackgroundImagePath string
}

type CharacterVoiceBehavior struct {
	CharacterID    string
	VoiceIndex     int64
	BehaviorIndex  int64
	Identification string
	ImagePath      string
}

type ChatMessage struct {
	SessionID      string
	CharacterID    string
	MessageIndex   int64
	Role           string
	Content        string
	ImageExtension string
	ImageData      []byte
}

type ChatSession struct {
	SessionID   string
	CharacterID string
}

type EnvConfig struct {
	ID                       int64
	OpenaiSpeechToTextApiKey string
	GoogleSpeechToTextApiKey string
	VoskServerEndpoint       string
	OpenaiApiKey             string
	AnthropicApiKey          string
	DeepseekApiKey           string
	GeminiApiKey             string
	OpenaiLocalApiKey        string
	OpenaiLocalApiEndpoint   string
	VoicevoxEndpoint         string
	Bertvits2Endpoint        string
	IrodoriTtsEndpoint       string
	NijivoiceApiKey          string
	Stylebertvit2Endpoint    string
	GoogleTextToSpeechApiKey string
	OpenaiSpeechApiKey       string
}

type GeneralConfig struct {
	ID                               int64
	Background                       string
	Language                         string
	SoundEffect                      int64
	CharacterOutputChange            int64
	EnableTtsOptimization            int64
	TranscriptionType                string
	TranscriptionMethod              string
	TranscriptionAutoThreshold       float64
	TranscriptionAutoSilentThreshold float64
	TranscriptionAutoAudioMinLength  float64
}

type MemoryItem struct {
	ID                int64
	PublicID          string
	CharacterID       string
	OwnerID           string
	Scope             string
	Kind              string
	Content           string
	NormalizedContent string
	KeywordsText      string
	Pinned            int64
	Confidence        float64
	Salience          float64
	Source            string
	SupersededBy      sql.NullInt64
	EmbeddingJson     string
	CreatedAt         string
	UpdatedAt         string
	LastAccessedAt    string
}

type MemoryJob struct {
	ID          int64
	Type        string
	Status      string
	UniqueKey   string
	PayloadJson string
	Attempts    int64
	AvailableAt string
	CreatedAt   string
	UpdatedAt   string
	LastError   string
}

type RateLimit struct {
	ID               string
	DayLastUpdate    string
	DayRequest       int64
	DayToken         int64
	HourLastUpdate   string
	HourRequest      int64
	HourToken        int64
	MinuteLastUpdate string
	MinuteRequest    int64
	MinuteToken      int64
}

type SessionSummary struct {
	OwnerID     string
	CharacterID string
	SessionID   string
	Summary     string
	UpdatedAt   string
}
