// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: rate_limits.sql

package sqlcgen

import (
	"context"
)

const getRateLimit = `-- name: GetRateLimit :one
SELECT id, day_last_update, day_request, day_token, hour_last_update, hour_request, hour_token, minute_last_update, minute_request, minute_token
FROM rate_limits
WHERE id = ?1
`

func (q *Queries) GetRateLimit(ctx context.Context, id string) (RateLimit, error) {
	row := q.db.QueryRowContext(ctx, getRateLimit, id)
	var i RateLimit
	err := row.Scan(
		&i.ID,
		&i.DayLastUpdate,
		&i.DayRequest,
		&i.DayToken,
		&i.HourLastUpdate,
		&i.HourRequest,
		&i.HourToken,
		&i.MinuteLastUpdate,
		&i.MinuteRequest,
		&i.MinuteToken,
	)
	return i, err
}

const listRateLimits = `-- name: ListRateLimits :many
SELECT id, day_last_update, day_request, day_token, hour_last_update, hour_request, hour_token, minute_last_update, minute_request, minute_token
FROM rate_limits
ORDER BY id
`

func (q *Queries) ListRateLimits(ctx context.Context) ([]RateLimit, error) {
	rows, err := q.db.QueryContext(ctx, listRateLimits)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []RateLimit
	for rows.Next() {
		var i RateLimit
		if err := rows.Scan(
			&i.ID,
			&i.DayLastUpdate,
			&i.DayRequest,
			&i.DayToken,
			&i.HourLastUpdate,
			&i.HourRequest,
			&i.HourToken,
			&i.MinuteLastUpdate,
			&i.MinuteRequest,
			&i.MinuteToken,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const upsertRateLimit = `-- name: UpsertRateLimit :exec
INSERT INTO rate_limits (
    id,
    day_last_update,
    day_request,
    day_token,
    hour_last_update,
    hour_request,
    hour_token,
    minute_last_update,
    minute_request,
    minute_token
) VALUES (
    ?1,
    ?2,
    ?3,
    ?4,
    ?5,
    ?6,
    ?7,
    ?8,
    ?9,
    ?10
)
ON CONFLICT(id) DO UPDATE SET
    day_last_update = excluded.day_last_update,
    day_request = excluded.day_request,
    day_token = excluded.day_token,
    hour_last_update = excluded.hour_last_update,
    hour_request = excluded.hour_request,
    hour_token = excluded.hour_token,
    minute_last_update = excluded.minute_last_update,
    minute_request = excluded.minute_request,
    minute_token = excluded.minute_token
`

type UpsertRateLimitParams struct {
	ID               string
	DayLastUpdate    string
	DayRequest       int64
	DayToken         int64
	HourLastUpdate   string
	HourRequest      int64
	HourToken        int64
	MinuteLastUpdate string
	MinuteRequest    int64
	MinuteToken      int64
}

func (q *Queries) UpsertRateLimit(ctx context.Context, arg UpsertRateLimitParams) error {
	_, err := q.db.ExecContext(ctx, upsertRateLimit,
		arg.ID,
		arg.DayLastUpdate,
		arg.DayRequest,
		arg.DayToken,
		arg.HourLastUpdate,
		arg.HourRequest,
		arg.HourToken,
		arg.MinuteLastUpdate,
		arg.MinuteRequest,
		arg.MinuteToken,
	)
	return err
}
